name: Electron Builder CI (WIN32)

on:
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v2
    - name: Installing Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Prepare for Windows Build
      shell: powershell #The default shell for Windows
      run: |
        git config --global core.autocrlf input
        (gc .\.gitmodules) -replace 'git@github.com:','https://github.com/' | Out-File -encoding ASCII .gitmodules
        git submodule update --init --recursive
        npm install -g yarn
        yarn install
        cd drawio/src/main/webapp
        yarn install
        cd ../..
    - name: Build for Windows (x32)
      shell: powershell #The default shell for Windows
      run: |
        #Disable auto-update and build 32bit first such that latest.yml is for 64bit only
        yarn run sync disableUpdate
        yarn run release-win32
